import { Inter } from "next/font/google";
import "./globals.css";
import SocketProvider from "./(portal)/compo/SocketProvider"; 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kiotel",
  description: "Kiotel tickets",
  icons: {
    icon: "/favicon.ico", // or use .png, .svg if you prefer
  },
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SocketProvider>
//           {children}
//         </SocketProvider>
//       </body>
//     </html>
//   );
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {/* PUT IT HERE! This guarantees it never unmounts, 
            no matter which module or folder you navigate to! */}
        <SocketProvider>
          {children}
        </SocketProvider>

      </body>
    </html>
  );
}
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Kiotel Hr Portal",
//   description: "Generated by create next app",  
//   icons: {
//     icon: "/Kiotel_Logo_bg.PNG", // or use .png, .svg if you prefer
//   },
  
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
